apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: sriov-dpdk-mlnx-connectx4
  annotations:
    k8s.v1.cni.cncf.io/resourceName: mellanox.com/mlnx_connectx4
spec:
  config: '{
    "type": "sriov",
    "name": "sriov-mlnx_connectx4"
}'
