apiVersion: v1
kind: Pod
metadata:
  name: testpmd
  annotations:
    k8s.v1.cni.cncf.io/networks: sriov-dpdk-mlnx-connectx5
spec:
  containers:
  - name: testpmd
    image: <DPDK testpmd image>
    imagePullPolicy: Never
    securityContext:
     capabilities:
        add: ["IPC_LOCK"]
    volumeMounts:
    - mountPath: /dev/hugepages
      name: hugepage
    resources:
      requests:
        memory: 1Gi
        hugepages-1Gi: 4Gi
        mellanox.com/mlnx_connectx5: 2
      limits:
        hugepages-1Gi: 4Gi
        mellanox.com/mlnx_connectx5: 2
    command: ["sleep", "infinity"]
  volumes:
  - name: hugepage
    emptyDir:
      medium: HugePages
